Removing unneeded mraa & node packages
Note: Setting NODE_PATH=/usr/lib/nodejs resulted in Segfaults & node require errors:

    [ 8978.483007] node[20082]: segfault at 3b0 ip b3297488 sp bfb8b5e0 error 4 in libmraa.so.2.0.0[b328f000+3a000]
    [ 9016.042555] node[20094]: segfault at 3b0 ip b3a9e488 sp bfd0d680 error 4 in libmraa.so.2.0.0[b3a96000+3a000]
    [ 9117.955505] mraa-i2c[20202]: segfault at 3b0 ip b7f53488 sp bfe13660 error 4 in libmraa.so.2.0.0[b7f4b000+3a000]
    [ 9141.844355] node[20214]: segfault at 3b0 ip b59cc488 sp bfb3d1f0 error 4 in libmraa.so.2.0.0[b59c4000+3a000]

module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

    Error: Module version mismatch. Expected 48, got 46.
        at Error (native)
        at Object.Module._extensions..node (module.js:604:18)
        at Module.load (module.js:494:32)
        at tryModuleLoad (module.js:453:12)
        at Function.Module._load (module.js:445:3)
        at Module.require (module.js:504:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/src/app/main.js:14:12)
        at Module._compile (module.js:577:32)
        at Object.Module._extensions..js (module.js:586:10)